### ISSUE TITLE
Command does not work: "That player cannot be found"

### ISSUE THREAD

**Issue by cheeseland-dev** [jasonwynn10/SimpleReplies#6]
### Issue description

- Expected result:` /r message` or `/reply message` would send a message to whoever sent you a message last or whoever you last sent a message to.
- Actual result: What actually happened? it responds with `That player cannot be found` as a message sent to whoever did `/r` even if the target player is online

### Steps to reproduce the issue
1. Have another player online
2. do `/msg {player} message`
3. do `/r message`
4. it will say `That player cannot be found`

### OS and versions

* Plugin Version: 1.0.2-1
* PocketMine-MP: 3.14.2
* PHP: The one that comes with 3.14.2
* Game version: Win10

### Other Plugins

```[15:15:56] [Server thread/INFO]: Plugins (60): AlwaysSpawn v2.2.4, AntiVoid v1.1.0, AuctionHouse v1.2.5, AutoClearLagg v3.1.0, BadWordBlocker v1.2.9, BanItem v2.3.3, BlocksConverter v2.0.2, BuilderTools v1.2.0-beta2, BurgerSpawners v0.1.4, ChatCensor v2.3, CrashTransfer v1.0.0, CustomAlerts v2.1, CustomAreas v1.2.1, CustomShopUI v4.0.5, DevTools v1.14.0, DoEmote v1.0.0, EC-TableUI v1.1.2-pre, EasyCommandAutofill v1.0.3, EconomyAPI v5.7.2, EmeraldWarp v1.0.1, FlyPE v2.0.2, FormAPI v1.3.0, GrapplingHook v1.0.3, InvCrashFix v0.0.1, InvSee v1.0.0, KeepInventory v1.0, MCPEToDiscord v1.4.1, MSpawns v2.2, MagicTelePortal v1.3.4, MaxEnchants v1.2.1, MineReset v3.2.0, MultiProtocol v1.0.0, MultiWorld v1.5.2, MysteryCrate v9.2.0, NanoCombinerGUI v1.0.1, NaviCompass v2.1.3, PiggyCustomEnchants v2.3.0, PiggyCustomEnchantsShop v1.3.5, PlayerSelectors v1.0.7, PlayerTags v1.0.7, PureChat v1.4.11, PureChatExtras v1.0.0, PureEntitiesX v0.6.6, PurePerms v1.4.3, RedstoneCircuit v1.0.1, Repair v1.0.1, Rewards v4.0, ScoreHud v5.2.0, ShulkerBox v1.0.2, SimpleReplies v1.0.2-1, SimpleWarp v4.0.1, SkyBlock v3.0.0, SkyBlockUI v1.1.0-beta6, Slapper v1.5.4, Texter v3.4.10, TimeCommander v1.0.2, TimeStopper v1.0.3, VanishV2 v1.8, WorldProtect v2.3.8, Worlds v3.0.4```
- If you remove all other plugins, does the issue still occur? **Yes**

### Console error, backtrace or other files

![image](https://user-images.githubusercontent.com/65053917/96304824-d1a51700-0fca-11eb-8957-c68927076d97.png)
^ works for not console too, I just did console for this screenshot

**Comment by jasonw4331** [comment]
The screenshot invalid because it's console. Please show evidence with a different individual. Also please test on a server without so many plugins.

**Comment by cheeseland-dev** [comment]
I managed to get the plugin working again, there seems to be an issue with the custom tell plugin (https://poggit.pmmp.io/p/customtell) which is a shame as its very nice for customizing the messages.

**Comment by jasonw4331** [comment]
Closing as a third party issue
